export const projectsdata = () => [
  {
    title: "A Modern Day Short-Blogging Platform",
    name: "AyeDot.com",
    banner: "/ayethumb.jpg",
    skills: [
      "TypeScript",
      "Next.js",
      "Redis",
      "Node.js",
      "Express",
      "Serverless",
      "CassandraDB",
      "MongoDB",
      "Postgre SQL Database",
      "AWS",
      "Cloudflare",
      "CSS3",
      "Tailwind",
    ],
    description: `Share your ideas and stories with the world on AyeDot - the platform for discovering and sharing exciting, informative content in form of multimedia short format mini blogs`,
    link: "/ayedot.com",
    github: null,
    logo: "ayecirclelogo.png",
    features: [
      "Easy Creation and Publishing of Short Format Mini Blogs using easy to user block based editor",
      "Creator Room for better content creation process",
      "Auto SEO Optimized Content",
      "Responsive and Mobile Friendly Layout.",
      "Engagement actions like Comments, Replies, Likes, Save, Shares on Miniblogs.",
      "Subscribe functionality for Personalized Feed",
      "Important Pages like User Channel, Studio, Creator Room, Block Base Editor, Trending, Saved, Settings, and many more",
    ],
    snapshots: [
      "/ayedot/ayedotmain-min",
      "/ayedot/blogpage-min",
      "/ayedot/profileayedot-min",
      "/ayedot/registerayedot-min",
      "/ayedot/trendingayedot-min",
    ],
    height: 1900,
    others: [
      {
        link: "/Projects/2",
        thumbnail: "/ayefanthumb.jpg",
        logo: "/ayefanlogo.jpg",
        title: "Ayefan - Social Media Platform",
        description: `Social media Webapp to connect, share your thoughts and feelings and communicate`,
      },
      {
        link: "/Projects/3",
        thumbnail: "/onwosthumb.jpg",
        logo: "/onwoslogo.jpg",
        title: "Onwos - Online Media Service Platform",
        description: `On Demand Media Service to stream and also create web series.`,
      },
    ],
  },
  {
    title: "Social media Webapp to connect, share your thoughts and feelings and communicate",
    name: "Ayefan - Social Media Platform",
    banner: "/ayefanthumb.jpg",
    skills: [
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Bootstrap",
      "CSS3",
    ],
    description: `A Social media Webapp to Social media Webapp to connect, share your thoughts, and feelings and communicate with people in form of Text, Audio, Video, and Photos.`,
    link: null,
    github: "https://github.com/helios-yamet/Social-Network-SDP",
    logo: "/ayefanlogo.jpg",
    features: [
      "Multimedia Posts in form of Text, Audio, Video, and Photos and Like, Share, Save, Comment and Reply features for engagement.",
      "Engagement actions like Like, Love, Share, Save, Comment and Reply on Posts.",
      "Follow and Unfollow functionality for Personalized Feed.",
      "Responsive and Mobile Friendly Layout.",
      "Communication system for users to communicate with each other in form of Text, Audio, Video, and Photos.",
      "Other important sections like User Profile, User Search, Trending Posts, Settings, Profile Avatar, Profile cover image or video and more.",
    ],
    snapshots: [
      "/ayefan/feeds4-min.png",
      "/ayefan/feed2-min.png",
      "/ayefan/feed1-min.png",
      "/ayefan/profile-min.png",
      "/ayefan/profile1.png",
      "/ayefan/create post-min.png",
      "/ayefan/cover video-min.png",
      "/ayefan/edit-min.png",
      "/ayefan/login-min-1.png",
      "/ayefan/search.png",
      "/ayefan/register.png",
    ],
    height: 1900,
    others: [
      {
        link: "/Projects/1",
        thumbnail: "/ayethumb.jpg",
        logo: "/ayelogo.jpg",
        title: "Ayedot - Short Blogging Platform",
        description: `Bloging Platform to Create and Publish Mini Blogs`,
      },
      {
        link: "/Projects/3",
        thumbnail: "/onwosthumb.jpg",
        logo: "/onwoslogo.jpg",
        title: "Onwos - Online Media Service Platform",
        description: `On Demand Media Service to stream and also create web series.`,
      },
      {
        link: "/Projects/4",
        thumbnail: "/firethumb.jpg",
        logo: "/firelogo.jpg",
        title: "fireflow - Anonymous Chat Rooms",
        description: `Instant messaging webapp to chat with people in groups`,
      },
    ],
  },
  {
    title: "Social media Webapp to connect, share your thoughts and feelings and communicate",
    name: "Onwos - Online Media Service",
    banner: "/onwosthumb.jpg",
    skills: [
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Bootstrap",
      "CSS3",
    ],
    description: `Online Media Service platform for streaming or creating web series with seasons.`,
    link: null,
    github: "https://github.com/helios-yamet/Onwos",
    logo: "/onwoslogo.jpg",
    features: [
      "Streaming Web series episodes and also creating web series with seasons and upload and publish easily.",
      "Follow shows and creators for updates on newly released episodes and shows.",
      "Responsive and Mobile Friendly Layout.",
      "Engagement elements - Like, Views, Share and Comment.",
      "Betters Shows Recommendation based on watch history and interests.",
      "Other important sections like Creators, Shows and Seasons Profile, Shows and Creators Search, Settings, Shows and Creators Profile Avatar and Cover image and more.",
    ],
    snapshots: [
      "/onwos/home-min.png",
      "/onwos/showsprofile-min.png",
      "/onwos/showsdetails-min.png",
      "/onwos/playpage-min.png",
      "/onwos/seasondetail-min.png",
      "/onwos/login-min.png",
      "/onwos/register-min.png",
    ],
    height: 1900,
    others: [
      {
        link: "/Projects/1",
        thumbnail: "/ayethumb.jpg",
        logo: "/ayelogo.jpg",
        title: "Ayedot - Short Blogging Platform",
        description: `Bloging Platform to Create and Publish Mini Blogs.`,
      },
      {
        link: "/Projects/4",
        thumbnail: "/firethumb.jpg",
        logo: "/firelogo.jpg",
        title: "fireflow - Anonymous Chat Rooms",
        description: `Instant messaging webapp to chat with people in groups.`,
      },
      {
        link: "/Projects/2",
        thumbnail: "/firethumb.jpg",
        logo: "/firelogo.jpg",
        title: "fireflow - Anonymous Chat Rooms",
        description: `Instant messaging webapp to chat with people in groups.`,
      },
    ],
  },
  {
    title: "Instant messaging Webapp to chat with people in groups",
    name: "fireflow - Chat Rooms",
    banner: "/firflowthumb.jpg",
    skills: [
      "JavaScript",
      "Node.js",
      "Express",
      "React",
      "Bootstrap",
      "CSS3",
      "MongoDB",
    ],
    description: `An Online anonymous temporary chat rooms platform that lets users create private chats rooms with secret codes and allows people to chat in groups. It is fully secured and anonymous as nothing is stored on the server. Everything is erased about you as soon as you log out.`,
    link: null,
    github: "https://github.com/helios-yamet/fireflow-chat-rooms",
    logo: "/firelogo.jpg",
    features: [
      "Create Anonymous temporary chat rooms with secret access codes.",
      "Group chatting with tracking how many people are online in the chat room.",
      "Fully Private as no data is stored on the server side.",
    ],
    snapshots: [
      "/fireflow/firefloe123-min.png",
      "/fireflow/homefire-min.png",
      "/fireflow/createroiom-min.png",
      "/fireflow/firef1-min.png",
      "/fireflow/joinroom-min.png",
    ],
    height: 1900,
    others: [
      {
        link: "/Projects/6",
        thumbnail: "/xporthumb.png",
        logo: "/xportlogo.jpg",
        title: "Xport - File Transfer Service",
        description: `A webapp to wasily share large file over the internet with your friends.`,
      },
      {
        link: "/Projects/1",
        thumbnail: "/ayethumb.jpg",
        logo: "/ayecirclelogo.png",
        title: "Ayedot - Short Blogging Platform",
        description: `Bloging Platform to Create and Publish Mini Blogs.`,
      },
      {
        link: "/Projects/2",
        thumbnail: "/ayefanthumb.jpg",
        logo: "/ayefanlogo.jpg",
        title: "Ayefan - Social Media Platform",
        description: `Social media Webapp to connect, share your thoughts and feelings and communicate`,
      },
    ],
  },
  {
    title: "Resume Shortlisting Service to find the best fit for the job.",
    name: "Shortlit - Resume Shortlisting Service",
    banner: "/shortthumb.jpg",
    skills: [
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Express",
      "Angular",
      "MongoDB",
      "Bootstrap",
      "CSS3",
    ],
    description: `An Online Service to help Companies to get the list of best suitable candidates for their job posts by just uploading their resumes. This Service automatically scans hundreds of resumes and matches them with job requirements and ranks them appropriately to get the list of best suitable candidates for the job role.`,
    link: null,
    github: "https://github.com/helios-yamet/Resume-Shortlisting-Application",
    logo: "/shortlogo.jpg",
    features: [
      "Scan and Process Resumes, obtaining the most suitable list of candidates, instead of manually reading all resumes.",
      "Feature for Companies to post jobs and Candidates to Apply for job.",
      "Responsive and Mobile Friendly Layout.",
      "Other important sections like Company Profile and Candidate Profile, Tracking the status of all job applications, Authentication, Settings, and more.",
    ],
    snapshots: [
      "/shortlit/Home 1-min.png",
      "/shortlit/profile user-min.png",
      "/shortlit/Home scroll down-min.png",
      "/shortlit/admin profile 1-min.png",
      "/shortlit/admin profile 2-min.png",
      "/shortlit/admin profile 3-min.png",
      "/shortlit/register user-min.png",
    ],
    height: 1900,
    others: [
      {
        link: "/Projects/1",
        thumbnail: "/ayethumb.jpg",
        logo: "/ayelogo.jpg",
        title: "Ayedot - Short Blogging Platform",
        description: `Bloging Platform to Create and Publish Mini Blogs.`,
      },
      {
        link: "/Projects/6",
        thumbnail: "/xporthumb.png",
        logo: "/xportlogo.jpg",
        title: "Xport - File Transfer Service",
        description: `A webapp to wasily share large file over the internet with your friends.`,
      },
    ],
  },
  {
    title: "Easily Share files and folders with your friends",
    name: "Xport - File Transfer Service",
    banner: "/xporthumb.png",
    skills: [
      "JavaScript",
      "Node.js",
      "React.js",
      "Express",
      "MongoDB",
      "Bootsrap",
      "CSS3",
    ],
    description: `An Online Service to easily Share large or small files of any format, with anyone around the world. `,
    link: null,
    github: "https://github.com/helios-yamet/Xport---OOSE-Project",
    logo: "/xportlogo.jpg",
    features: [
      "Upload and share any file of size upto 1GB of any format like text file, images, videos, application, pdf, excel, ppt and more.",
      "Other important sections like User Profile, Tracking of number of files shared, amount of data transported, authentication and more.",
    ],
    snapshots: [
      "/xport/Send1-min.png",
      "/xport/send2-min.png",
      "/xport/send3-min.png",
      "/xport/Recieve-min.png",
      "/xport/User profile-min.png",
      "/xport/login-min.png",
      "/xport/register-min.png",
      "/xport/edit account-min.png",
      "/xport/delete-min.png",
    ],
    height: 1900,
    others: [
      {
        link: "/Projects/5",
        thumbnail: "/shortthumb.jpg",
        logo: "/shortlogo.jpg",
        title: "Shortlit - Resume Shortlisting Service",
        description: `Resume Shortlisting Service to find the best fit for
                          the job.`,
      },
      {
        link: "/Projects/4",
        thumbnail: "/firflowthumb.jpg",
        logo: "/firelogo.jpg",
        title: "fireflow - Anonymous Chat Rooms ",
        description: `Instant messaging webapp to chat with people in
                          groups.`,
      },
    ],
  },
];
